spring:
  datasource:
    username: root
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.0.109:4306/gulimall_sms
  application:
    name: service-sms
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.0.109:8848
  mvc:
    format:
      date: yyyy-MM-dd HH:mm:ss
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
server:
  port: 8007

