spring:
  application:
    name: service-seckill
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.0.109:8848
  redis:
    host: 192.168.0.109
    port: 6379
  task:
    execution:
      pool:
        core-size: 5
        max-size: 10
        queue-capacity: 100
  session:
    store-type: redis
server:
  port: 8410