spring:
  application:
    name: service-seckill
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.0.109:8848
    sentinel:
      transport:
        port: 8719
        dashboard: 192.168.0.109:8858
        clientIp: 192.168.0.41
  redis:
    host: 192.168.0.109
    port: 6379
  task:
    execution:
      pool:
        core-size: 5
        max-size: 10
        queue-capacity: 100
  session:
    store-type: redis
  #    redis:
  #      namespace: gulimall:session
  rabbitmq:
    addresses: 192.168.0.109
    virtual-host: /
  thymeleaf:
    cache: false
server:
  port: 8410
