spring:
  application:
    name: service-auth
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.0.109
  thymeleaf:
    cache: false
  redis:
    host: 192.168.0.109
  session:
    store-type: redis
#    redis:
#      namespace: gulimall:session
server:
  port: 8150
wechat:
  app-id: wxed9954c01bb89b47
  app-secret: a7482517235173ddb4083788de60b90e
  redirect-url: http://guli.shop/api/ucenter/wx/callback