spring:
  application:
    name: api-gateway
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.0.109:8848
      config:
        enabled: true
    gateway:
      routes:
        - id: product_route
          uri: lb://service-pms
          predicates:
            - Path=/api/product/**
          filters:
            - RewritePath=/api/(?<segment>.*),/$\{segment}

        - id: third_part_route
          uri: lb://service-third-part
          predicates:
            - Path=/api/third-part/**
          filters:
            - RewritePath=/api/(?<segment>.*),/$\{segment}

        - id: member_route
          uri: lb://service-ums
          predicates:
            - Path=/api/member/**
          filters:
            - RewritePath=/api/(?<segment>.*),/$\{segment}

        - id: coupon_route
          uri: lb://service-sms
          predicates:
            - Path=/api/coupon/**
          filters:
            - RewritePath=/api/(?<segment>.*),/$\{segment}

        - id: ware_route
          uri: lb://service-wms
          predicates:
            - Path=/api/ware/**
          filters:
            - RewritePath=/api/(?<segment>.*),/$\{segment}

        - id: order_route
          uri: lb://service-oms
          predicates:
            - Path=/api/product/**
          filters:
            - RewritePath=/api/(?<segment>.*),/$\{segment}

        - id: search_route
          uri: lb://service-search
          predicates:
            - Path=/api/search/**
          filters:
            - RewritePath=/api/(?<segment>.*),/$\{segment}

        - id: admin_route
          uri: lb://renren-fast
          predicates:
            - Path=/api/**
          filters:
            - RewritePath=/api/(?<segment>.*),/renren-fast/$\{segment}

        - id: search_host_route
          uri: lb://service-search
          predicates:
            - Host=search.gulimall.com

        - id: item_host_route
          uri: lb://service-pms
          predicates:
            - Host=item.gulimall.com

        - id: auth_host_route
          uri: lb://service-auth
          predicates:
            - Host=auth.gulimall.com

        - id: cart_host_route
          uri: lb://service-cart
          predicates:
            - Host=cart.gulimall.com

        - id: order_host_route
          uri: lb://service-oms
          predicates:
            - Host=order.gulimall.com

        - id: member_host_route
          uri: lb://service-ums
          predicates:
            - Host=member.gulimall.com

        - id: product_host_route
          uri: lb://service-pms
          predicates:
            - Host=gulimall.com
