spring:
  application:
    name: service-cart
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.0.109
    sentinel:
      transport:
        port: 8719
        dashboard: 192.168.0.109:8858
        clientIp: 192.168.0.41
  redis:
    host: 192.168.0.109
    port: 6379
server:
  port: 8010