spring:
  datasource:
    username: root
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.0.109:4306/gulimall_pms
  application:
    name: service-pms
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.0.109:8848
  redis:
    host: 192.168.0.109
    port: 6379
  main:
    allow-bean-definition-overriding: true
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
  thymeleaf:
    cache: false
  cache:
    type: redis
    redis:
      use-key-prefix: true
      cache-null-values: true
      time-to-live: 36000
server:
  port: 8004

mybatis-plus:
  global-config:
    db-config:
      logic-delete-value: 1
      logic-not-delete-value: 0
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

thread:
  pool:
    core-pool-size: 20
    maximum-pool-size: 30
    keep-alive-time: 10