spring:
  datasource:
    username: root
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.0.109:4306/gulimall_pms
  application:
    name: service-pms
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.0.109:8848
  redis:
    host: 192.168.0.109
    port: 6379
server:
  port: 8004

mybatis-plus:
  global-config:
    db-config:
      logic-delete-value: 1
      logic-not-delete-value: 0
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl


