spring:
  application:
    name: service-search
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.0.109:8848
        namespace: public
  elasticsearch:
    rest:
      uris: http://192.168.0.109:9200
  thymeleaf:
    cache: false
server:
  port: 8008
