spring:
  application:
    name: service-search
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.43.109:8848
  elasticsearch:
    rest:
      uris: http://192.168.43.109:9200
server:
  port: 8009
